name: 'rabbitmq_compose'

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    hostname: "rabbitmq-host"
    environment:
      - "RABBITMQ_DEFAULT_USER=guest"
      - "RABBITMQ_DEFAULT_PASS=guest"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq/config:/etc/rabbitmq"
      - "./rabbitmq/log:/var/log/rabbitmq"
      - "./rabbitmq/mnesia:/var/lib/rabbitmq/mnesia"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 3