name: 'rabbitmq_compose'

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    environment:
      - "RABBITMQ_DEFAULT_USER=user"
      - "RABBITMQ_DEFAULT_PASS=password"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq:/etc/rabbitmq"